#!/bin/bash

# From http://stackoverflow.com/a/21188136/446554
get_abs_filename() {
    # $1 : relative filename
    echo "$(cd "$(dirname "$1")" && pwd)/$(basename "$1")"
}

INSTALL_SCRIPT_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
DEFAULT_CONFIG_FILENAME="default.config"
HOME_CONFIG_FILENAME="${HOME}/.multi"
ETC_CONFIG_FILENAME="/etc/multi"
EXECUTABLE="multi"
INSTALLED_EXECUTABLE="/usr/local/bin/${EXECUTABLE}"
EXECUTABLE_SOURCE=$(get_abs_filename "./${EXECUTABLE}")

# Install the default config file in the user's home directory
if [[ ! -f $HOME_CONFIG_FILENAME ]]; then
    echo "Copying default config to $HOME_CONFIG_FILENAME"
    cp "${INSTALL_SCRIPT_DIR}/$DEFAULT_CONFIG_FILENAME" "$HOME_CONFIG_FILENAME"
fi

# Install the default config file into /etc
if [[ ! -f $ETC_CONFIG_FILENAME ]]; then
    echo "Copying default config to $ETC_CONFIG_FILENAME"
    sudo cp "${INSTALL_SCRIPT_DIR}/$DEFAULT_CONFIG_FILENAME" "$ETC_CONFIG_FILENAME"
fi

if [[ ! -L $INSTALLED_EXECUTABLE ]]; then
    echo "Installing $EXECUTABLE to $INSTALLED_EXECUTABLE"
    ln -s "${INSTALL_SCRIPT_DIR}/$EXECUTABLE_SOURCE" "$INSTALLED_EXECUTABLE"
fi
