#!/bin/bash

CONFIG_FILE=".multi"
GLOBAL_CONFIG_FILE="/etc/multi"
HOME_CONFIG_FILE="${HOME}/${CONFIG_FILE}"

if [[ -f $CONFIG_FILE ]]; then
    source $CONFIG_FILE
elif [[ -f $HOME_CONFIG_FILE ]]; then
    source $HOME_CONFIG_FILE
elif [[ -f $GLOBAL_CONFIG_FILE ]]; then
    source $GLOBAL_CONFIG_FILE
fi

if [[ -z "$1" ]]; then
    echo "Expects at least one argument"
    exit 1
fi

if [[ -z "$REPOS" ]]; then
    echo "You have not defined any repositories to search. Please fill in the REPOS variable in your ~/${CONFIG_FILE} file."
    exit 1
fi

if [[ -z "$BASE_DIR" ]]; then
  BASE_DIR=$(pwd)
else
  BASE_DIR="${BASE_DIR/#\~/$HOME}"
fi

for REPO in $REPOS; do
    REPO_DIR="${BASE_DIR}/${REPO}"
    if [[ -d "$REPO_DIR" ]]; then
        cd $REPO_DIR
        echo $REPO
        echo "===================================================="
        GIT_PAGER='' git grep $GIT_GREP_OPTIONS "$@"
        cd $base_path
    fi
done
